### ISSUE TITLE
VAExtensions not working

### ISSUE THREAD

**Issue by mikelimtw** [Antaniserse/VAExtensions#1]
Hi Antaniserse,

I followed your directions and copied the VAExtensions folder into VoiceAttack/Apps, but VA doesn't recognize the plugin. I notice that your files are not .dll's. I'm now assuming that I need to have VisualBasic.NET installed so that this will run?

**Comment by andrei-zgirvaci** [comment]
You should download last .zip file not source files, https://github.com/Antaniserse/VAExtensions/releases

**Comment by Antaniserse** [comment]
Yes, as noted by [MD3XTER](https://github.com/MD3XTER), the binary packages are always under '[Releases](https://github.com/Antaniserse/VAExtensions/releases)'

Just unzip inside your VoiceAttack 'Apps' subfolder and you are good to go
