### ISSUE TITLE
Read json throws exception

### ISSUE THREAD

**Issue by crankfelix** [Antaniserse/VAExtensions#2]
While trying to use the read json functionality, i'll always get an exception:

`16:59:39 - Error reading XML: Data at the root level is invalid. Line 1, position 1.`

This is the case with my own JSON file as well as with the provided example.

**Comment by Antaniserse** [comment]
Yes, there's a typo in the sample profile: 
In the "execute external plugin function" screen, the "plugin context" textbox should be set to **read_json** instead of **read_xml**
